### ISSUE TITLE
When the Account object is stored?

### ISSUE THREAD

**Issue by kennyhorna** [spatie/laravel-event-projector-demo-app#3]
Hello, nice package btw (laravel-event-projector).

I don't know if its lack of sleep but I'm having a hard time to understand when the `Account` object is persisted. I mean this are the steps when creating an account:

1. Call to the static method `createWithAttributes()`
2. Inside the method a `Uuid` is generated and added to the array of attributes to persist.
3. An event is fired. In the docs says that this events handle the object creation.
4. The `Uuid` is used to find the persisted  `Account` object and returned.

Now inside the event class, where the model is persisted there is only this code:

```php
<?php
namespace App\Events;
use Spatie\EventProjector\ShouldBeStored;
class AccountCreated implements ShouldBeStored
{
    /** @var string */
    public $accountUuid;

    /** @var array */
    public $accountAttributes;

    public function __construct(array $accountAttributes)
    {
        $this->accountUuid = $accountAttributes['uuid'];

        $this->accountAttributes = $accountAttributes;
    }
}
```

The constructor just receive the values, how does this persist the model?

I know this is a simple (even silly?) question but I'd like to know how this works in order to apply it in my code. 

Thanks in advance.

**Comment by freekmurze** [comment]
It gets stored in the projector: https://github.com/spatie/laravel-event-projector-demo-app/blob/e80b0c7294bc1bbbb6dfe76a81fa6ef835d81a40/app/Projectors/AccountBalanceProjector.php#L31
